sudo: true
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_575a7f776184_key -iv $encrypted_575a7f776184_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- export PATH=$(pwd)/assets:$PATH
- sfdx plugins:install salesforcedx@41.2.0
#- sfdx update alpha
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- ./testing.sh nop
# - sfdx force:org:open -u HubOrg
# - sfdx force:project:create -n geolocation
#- cd geolocation
#- sfdx force:org:create -s -f config/project-scratch-def.json -a GeoAppScratch
#- sfdx force:limits:api:display -u ciorg
#- sfdx force:source:push -u ciorg
#- sfdx force:apex:test:run -u ciorg -c -r human
#- sfdx force:org:delete -u ciorg -p
